version: "3.8"

# Services
services:
    # Nginx Service
    nginx:
        image: nginx:1.19-alpine
        # ports:
        #     - 8080:80
        volumes:
            - ./src:/var/www/php
            - ./.docker/nginx/conf.d:/etc/nginx/conf.d
        environment:
            VIRTUAL_HOST: php.test
        depends_on:
            - php

    # PHP Service
    php:
        build: ./.docker/php
        working_dir: /var/www/php
        volumes:
            - ./src:/var/www/php:cached
            - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        depends_on:
            - mysql

    # MySQL Service
    mysql:
        image: mysql:8
        environment:
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
            - mysqldata:/var/lib/mysql
            - ./.docker/mysql/initdb:/docker-entrypoint-initdb.d
        ports:
            - 33060:3306

    memcached:
        image: memcached:latest

# Volumes
volumes:
    mysqldata:

networks:
    default:
        external: true
        name: nginx-proxy
